version: 2.1

jobs:
  focal_gcc9_coverage:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_coverage.sh
  focal_gcc9_asan:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_asan.sh
  ubuntu_arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_ubuntu_arm64.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    - focal_gcc9_coverage
    - focal_gcc9_asan
    - focal_gcc9_docs
    - ubuntu_arm64
